name: bankeep
description: "The ultimate mobile app companion for seamless banking experiences."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  animate_do: ^3.0.2
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.5
  google_fonts: ^6.2.1
  http: ^1.2.2
  iconly: ^1.0.1
  iconsax: ^0.0.8
  my_formfield: ^0.0.1
  provider: ^6.0.5
  # rive: ^0.13.15
  shared_preferences: ^2.1.0
  smooth_page_indicator: ^1.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/
    - lib/assets/icons/
    - lib/assets/illustrations/
    - lib/assets/animations/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
